module.exports = {
  ci: {
    collect: {
      url: ["http://localhost:3000"],
      startServerCommand: "npm run start",
      numberOfRuns: 1,
      // settings: {
      //   preset: "desktop",
      // },
    },
    assert: {
      assertions: {
        // keep the threshold low because that 0.75 is max performance score generated by lightHouse CI
        "categories:performance": ["error", { minScore: 0.7 }],
        "categories:best-practices": ["error", { minScore: 0.9 }],
        "categories:accessibility": ["warn", { minScore: 0.9 }],
        "categories:seo": ["warn", { minScore: 0.9 }],
      },
      // preset: "lighthouse:recommended",
    },
    upload: {
      target: "temporary-public-storage",
    },
  },
};
