# ./.github/workflows/lighthouse.yml
name: LighthouseCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# jobs:
#   lighthouse:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup node
#         uses: actions/setup-node@v1
#         with:
#           node-version: "14.x"

#       - name: Build
#         run: |
#           npm install
#           npm run build
#           npm start

#       - name: run Lighthouse CI
#         run: |
#           npm install -g @lhci/cli@0.4.x
#           lhci autorun

# name: Lighthouse Check
# on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: mkdir /tmp/artifacts

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          install: npm install
          build: npm run build
          start: npm start
          outputDirectory: /tmp/artifacts
          urls: "https://www.foo.software,https://www.foo.software/contact"

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
